import 'package:get/get.dart';

class MyTranslation extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    "ar" : {
      "1" : "اختر اللفة",
      "2" : "الانكليزية",
      "3" : "العربية",
      "4" : "اهلا وسهلا غي تطبيقنا",
      "Alert" : "تنبيه",
      "Do you want to exit the application ?" : "هل تريد الخروج من التطبيق؟" ,
      "Yes" :"نعم" ,
      "No"  : "لا",
      "not valid username" : "اسم مستخدم غير صالح",
      "not valid email" : "بريد إلكتروني غير صالح",
      "not valid phone" :  "هاتف غير صالح",
      "Does not have product" : "ليس لديه منتج" ,
      "can't be Empty" : "لا يمكن أن تكون فارغة",
      "can't be less than " :  "لا يمكن أن يكون أقل من ",
      "can't be larger than" : "لا يمكن أن يكون أكبر من",
      "My Cart" : "السلة",
      'Checkout' : 'تأكيد الطلب',
      "Choose Payment Method :" : "اختر طريقة الدفع :",
      'Cash ' :'كاش',
      'Payment Card' :  'بطاقة الدفع',
      "Choose Delivery Type :" : "اختر نوع التسليم :" ,
      'Delivery' : 'توصيل',
      'Shipping' :'الشحن' ,
      "Choose Address :" : "اختر العنوان :",
      "Address" :  "العنوان",
      "Enter your Address" : "أدخل عنوانك",
      "My Favorite" : "المفضلة",
      "loading..." :  "تحميل...",
      'Forget Password !! ' :  'نسيت كلمة المرور !! ',
      "email" :  "البريد الإلكتروني",
      "Enter your Email" : "أدخل بريدك الإلكتروني",
      'Check' : 'تحقق',
      //home page
      "Find Product" : "البحث عن المنتج",
      "A huge surprise" : "مفاجأة كبيرة",
      " Discounts up to 40%" :"خصومات تصل إلى 40٪",
      "Categories:" : "الفئات:",
      "High Rating Product:" : "منتجات الأعلى تقييماً:",
      "Discount Products:" : "منتجات التخفيضات:",
      "Products with the highest rating:" : "منتجات ذات تقييم الاعلى",
      'Login' : 'تسجيل الدخول',
      "Email" :  "البريد الإلكتروني",
      "password" : "كلمة المرور",
      "Enter your password" :"أدخل كلمة المرور الخاصة بك" ,
      'Forget Password ?' : 'نسيت كلمة المرور ؟',
      'ReGister' : 'تسجيل' ,
      //onbording
      'Welcome to' :  'مرحبا بكم في!',
      'We\'re thrilled to have you join our online Stupify shop.' : 'نحن يسعدنا أن تنضم إلى متجر الغباء عبر الإنترنت.',
      'Explore Our Product Categories' :  'استكشف فئات منتجاتنا',
      '11' : 'تصفح من خلال فئات المنتجات بديهية لدينا والعثور على رفيق التكنولوجيا المثالي لنمط حياتك ، واكتشاف مجموعة واسعة من الالكترونيات مصممة خصيصا لاحتياجاتك',
      'Let\'s Get Started!' : 'دعونا نبدأ!',
      '12' : ' الآن بعد أن عرفت ما يمكن توقعه ، حان الوقت للشروع في مغامرة التسوق الخاصة بك. انغمس في عالم من الابتكار والراحة والأسعار التي لا تقبل المنافسة. استمتع بتجربة تسوق سلسة عبر الإنترنت في ',
      'Happy shopping!' : 'تجربة ممتعة.',
      'SKIP' : 'تخطي',
      "My Order": "طلباتي",
      "Order Number : " : "رقم الطلب : ",
      "Home" : "الرئيسية",
      "Order" : " طلباتي",
     "Favorite" :  "المفضلة",
      "Setting" : "الاعدادات",
      'Go to cart' : 'اذهب إلى السلة',
      "Rating" : "التقييم",
      "About Product:" : "حول المنتج:",
      "Details :" : "التفاصيل :",

      //register
      'Register': 'تسجيل' ,
      "Username" : "اسم المستخدم",
      "Enter your Username" : "أدخل اسم المستخدم الخاص بك",
      "Phone" :"هاتف",
      "Enter your Phone" : "أدخل هاتفك",
      " have an account ? " :  "لديك حساب ؟ ",
      'Success ' : 'النجاح',
      'Register Completed Successfully' :  'اكتمل التسجيل بنجاح',
      ' Go To Login' :  'الذهاب إلى تسجيل الدخول',
      'Verification Code ' :  'رمز التحقق',
      'Please enter the Verification code of your email !' :  'الرجاء إدخال رمز التحقق من البريد الإلكتروني الخاص بك !',
      ' New Password ':  'كلمة مرور جديدة',
      'Please enter the new password' :  'الرجاء إدخال كلمة المرور الجديدة',
      'Register Completed Successfully' : 'اكتمل التسجيل بنجاح',
      ' Go To Login':'الذهاب إلى تسجيل الدخول',
      "Dark mode" :  "الوضع المظلم",
      "About us":"من نحن",
      "Contact us" : "اتصل بنا",
       "Logout": "تسجيل الخروج",
      "Language": "اللغة"






    },
    "en" : {
      "1" : "Choose Language",
      "2" : "English",
      "3" : "Arabic",
      "4" : "On Board 1 Title",
      "Alert" : "Alert",
      "Do you want to exit the application ?" : "Do you want to exit the application ?",
      "Yes" : "Yes",
      "No" : "No",
      "not valid username" : "not valid username",
      "not valid email" : "not valid email",
      "not valid phone" : "not valid phone",
      "Does not have product" : "Does not have product",
      "can't be Empty":"can't be Empty",
      "can't be less than " : "can't be less than ",
      "can't be larger than" : "can't be larger than",

      //cart
      "My Cart" : "My Cart",
      //checkout
      'Checkout' : 'Checkout',
      "Choose Payment Method :" :  "Choose Payment Method :",
      'Cash ' :  'Cash ',
      'Payment Card' : 'Payment Card',
      "Choose Delivery Type :" : "Choose Delivery Type :",
      'Delivery' : 'Delivery',
      'Shipping' : 'Shipping',
      "Choose Address :" :"Choose Address :",
      "Address" : "Address",
      "Enter your Address" : "Enter your Address",
      "My Favorite" : "My Favorite",

      //checkpassword
      "loading..." : "loading...",
      'Forget Password !! ' : 'Forget Password !! ',
      "email" : "email" ,
      "Enter your Email" : "Enter your Email",
      'Check' : 'Check',

      //homepage
      "Find Product" : "Find Product",
      "A huge surprise" : "A huge surprise",
      " Discounts up to 40%" :  " Discounts up to 40%",
      "Categories:" : "Categories:",
      "Discount Products:" :  "Discount Products:",
      "High Rating Product:" : "High Rating Product:",
      "Products with the highest rating: " : "Products with the highest rating: ",
      //login
      'Login' : 'Login' ,
      "Email" : "Email",
      "password" : "password",
      "Enter your password" : "Enter your password",
      'Forget Password ?' : 'Forget Password ?',
      'ReGister' : 'ReGister',
      //onbording
      'Welcome to' : 'Welcome to',
      'We\'re thrilled to have you join our online Stupify shop.' : 'We\'re thrilled to have you join our online Stupify shop.',
      'Explore Our Product Categories' : 'Explore Our Product Categories',
      '11' : 'Browse through our intuitive product categories and find the perfect tech companion for your lifestyle, Discover a vast range of electronics tailored to your needs',
       'Let\'s Get Started!' : 'Let\'s Get Started!',
      '12' : 'Now that you know what to expect, it\'s time to embark on your shopping adventure. Dive into a world of innovation, convenience, and unbeatable prices. Enjoy a seamless online shopping experience at ',
      'Happy shopping!' : 'Happy shopping!',
      'SKIP' : 'SKIP',

      //order
      "My Order" : "My Order",
      "Order Number : " : "Order Number : ",

      //bottombar
      "Home" : "Home",
      "Order" : "Order",
      "Favorite" : "Favorite" ,
      "Setting" : "Setting",

      //product details
      'Go to cart' : 'Go to cart',
      "Rating" : "Rating",
      "About Product:" : "About Product:",
      "Details :" : "Details :",

      //register
      'Register' : 'Register',
      "Username" : "Username",
      "Enter your Username" : "Enter your Username",
      "Phone" : "Phone",
      "Enter your Phone" : "Enter your Phone",
      " have an account ? " : " have an account ? ",
      'Success ' : 'Success ',
      'Register Completed Successfully' : 'Register Completed Successfully',
      ' Go To Login' : ' Go To Login',
      'Verification Code ' : 'Verification Code ',
      'Please enter the Verification code of your email !' : 'Please enter the Verification code of your email !',
      ' New Password ' : ' New Password ',
      'Please enter the new password' : 'Please enter the new password',
      'Register Completed Successfully' : 'Register Completed Successfully',
      ' Go To Login' : ' Go To Login',
      "Dark mode" : "Dark mode",
      "About us" : "About us",
      "Contact us" :"Contact us",
      "Logout" : "Logout",
      "Language":"Language",

    },
  };
}